### ISSUE TITLE
Building on RaspberryPi

### ISSUE THREAD

**Issue by tomjon** [hcr923fm/chronicle#30]
Hi, I adapted the Linux portion of the Makefile to enable me to build chronicle on Raspberry Pi.  I also needed as an additional prereq libpulse-dev.

    PIFLAGS=`rtaudio-config --cxxflags` `rtaudio-config --cppflags` `rtaudio-config --libs`
    CURSESFLAGS=`pkgconfig --cflags --libs ncurses`
    
    pi:
            mkdir -p build/pi
            g++ $(FILES) -std=c++11 -lpthread $(PIFLAGS) $(MSYS2LINBOOSTLIBS) $(CURSESFLAGS) -o build/pi/chronicle
            cp README.md build/pi
            cp LICENCE build/pi
            cp CHANGELOG.md build/pi

**Comment by mtunstill** [comment]
@tomjon - does it fully work and are you supplying another audio device to capture audio?

**Comment by calmcl1** [comment]
@tomjon this looks fun! How far did you get with it? Also, what did you need `libpulse-dev` for? Is RtAudio compiling with PulseAudio support by default? What is the output of `pkg-config --libs --cflags rtaudio`?

Also, looking at the RtAudio source, I suspect that calls to `rtaudio-config` might be made unnecessary in the next version... 👍

**Comment by calmcl1** [comment]
It's been a while, I know - but if you're interested, there's now a proper autotools setup for Chronicle, so you should be able to autogenerate the correct Makefile and build Chronicle just by running `./autogen.sh && ./configure && make`. Saves on hand-editing Makefiles and trying to guess library setups ;)

**Comment by calmcl1** [comment]
It's been a while, but this should now be possible to build easily enough on a RPi now that chronicle has switched over to a CMake build system :)

You'll still need to install the dependencies (though most can be installed from a package manager). Just be aware that AFAIK, the latest versions of `spdlog`, `boost`, and `cmake` that are available in `apt` are a few versions out of date, so you will probably need to compile them separately.

**Comment by calmcl1** [comment]
Have successfully just tested this build on a Raspberry Pi - hurrah!
